---
- hosts: all
  become: true

  tasks:
    -name: Print all the ansible gathered_facts
     ansible.builtin.debug:
       var: ansible_facts

    -name: Stop the ubuntu instances only
     ansible.builtin.command: /sbin/shutdown -t now
     when: 
      ansible_facts['os_family'] == "Debian"
      

