---
- hosts: localhost
  connection: local
  tasks: 
  - name: Create EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "AWS-Linux"
      instance_type: "t2.micro"
      security_groups: default
      region: "ap-south-1"
      aws_access_key: "{{ec2_access_keys}}"
      aws_secret_key: "{{ec2_secret_keys}}"
      network:
        assign_public_ip: yes
      image_id: "{{ item.image}}"
    loop:
      - { image: "ami-084568db4383264d4", name: "managed-1" }
      - { image: "ami-084568db4383264d4", name: "maanged-2" }
      - { image: "ami-0779caf41f9ba54f0", name: "managed-3" }